crowdfunding/urls.py
from django.contrib import admin
from django.urls import path, include
from landingpage import views as landing_views
from register.views import log_out
from django.contrib.auth import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from form_donasi.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_views.landingPage, name="landingpage"),
    path('program/', include('program.urls')),
    path('register/', include('register.urls')),
    path('form_donasi/', include('form_donasi.urls', namespace="form_donasi")),
    path('listDonatur/', include('programdonatur.urls')),
    path('listDonasi/', include('daftardonasi.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('tentangKami/', include('testimoni.urls')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

form_donasi/urls.py
from django.conf.urls import url
from django.urls import path

from .views import form_donasi_post, index

app_name = 'form_donasi'

urlpatterns = [
    path('', index, name='index'),
    path('form_donasi_post', form_donasi_post, name='form_donasi_post')
]

program/urls.py
from django.urls import path
from .views import program_view

urlpatterns = [
    path('<str:judul>', program_view)
]

form_donasi/models.py
from django.db import models
from .forms import *

# Create your models here.
class formDonasiModels(models.Model):
    nama_program = models.CharField(max_length = 1000000, choices = PROGRAM_CHOICES)
    nama_lengkap = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    jumlah_uang = models.BigIntegerField()
    dukungan = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)

form_donasi/forms.py
from django import forms

PROGRAM_CHOICES = (
    ("Bersama, Bantu Palu, Donggala", ("Bersama, Bantu Palu, Donggala")),
    ("Kami Terancam Hanyut, Butuh Jembatan", ("Kami Terancam Hanyut, Butuh Jembatan")),
)

class submitDonasiForm(forms.Form):
    nama_program = forms.ChoiceField(choices=PROGRAM_CHOICES, label="Program")#, initial='', widget=forms.Select(), required=True)
    nama_lengkap = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'class': 'form-control',
                                                                 'placeholder': "Nama Lengkap"}))
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(attrs={'type': 'email',
                                                                     'placeholder': 'Alamat E-Mail'}))
    jumlah_uang = forms.IntegerField(required=True, label='', widget=forms.TextInput(attrs={'type': 'number',
                                                                     'placeholder': 'Jumlah uang yang ingin didonasikan',
                                                                          'min':'10000'}))
    dukungan = forms.CharField(required=True, label='',
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': "Dukungan untuk sahabat kita"}))

form_donasi/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import submitDonasiForm
from .models import formDonasiModels
from register.models import InputDonatur

def index(request):
    isiForms = formDonasiModels.objects.all()
    response = {'forms': submitDonasiForm, 'result': isiForms}
    return render(request, 'form_donasi.html', response)

def form_donasi_post(request):
    response = {}
    if request.method == "POST":
        cekAnonim = request.POST.getlist('cekAnon')
        if(cekAnonim):
            response['nama_lengkap'] = request.POST['nama_lengkap']
        else :
            response['nama_lengkap'] = 'Anonymous'
        response['nama_program'] = request.POST['nama_program']
        response['email'] = request.POST['email']
        response['jumlah_uang'] = request.POST['jumlah_uang']
        response['dukungan'] = request.POST['dukungan']
        forms = formDonasiModels(nama_program=response['nama_program'], nama_lengkap=response['nama_lengkap'], email=response['email'], jumlah_uang=response['jumlah_uang'], dukungan=response['dukungan'])
        if request.user.is_authenticated:
            if request.user.email == request.POST['email']:
                forms.save()
                return HttpResponseRedirect('/listDonatur')
        return HttpResponseRedirect('/form_donasi')
    else :
        return HttpResponseRedirect('/form_donasi')

form_donasi/templates/form_donasi.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Form Donasi</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/LPStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/RegisterStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/DonasiStyle.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
{% include "navbar.html" %}
<div class="container-fluid h-100 background_register">
    <div class="row h-100 justify-content-center align-items-center">
            <div class="contaier_form" style="padding-bottom: 8%">
                <div class="container_form">
                    <div class="judul_utama">
                        <h3 style="font-family:'Montserrat', sans-serif; font-size: 30px; text-align: center; color:black">Anda akan
                            <span style="font-weight:bold">berdonasi</span></h3>
                        <h3 style="font-family:'Montserrat', sans-serif; font-size: 30px; text-align: center; color:black">untuk
                            membantu <span style="font-weight:bold">mereka</span></h3> <br>
                    </div>

                    <form action={% url 'form_donasi:form_donasi_post' %} method="POST">
                        {% csrf_token %}
                        {{ forms.as_p }}
                    <input type="checkbox" name="cekAnon" value="1">Tampilkan nama donatur<br>
                    <div class='submit_button' >
                        <input type='submit' value='Donasi'>
                    </div>
                    </form>
                </div>
            </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>