crowdfunding/urls.py
from django.contrib import admin
from django.urls import path, include
from landingpage import views as landing_views
from register.views import log_out
from django.contrib.auth import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from form_donasi.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_views.landingPage, name="landingpage"),
    path('program/', include('program.urls')),
    path('register/', include('register.urls')),
    path('form_donasi/', include('form_donasi.urls', namespace="form_donasi")),
    path('listDonatur/', include('programdonatur.urls')),
    path('listDonasi/', include('daftardonasi.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('tentangKami/', include('testimoni.urls')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

daftardonasi/urls.py
from django.conf.urls import url
from django.urls import path

from .views import listDonasi

app_name = 'daftardonasi'

urlpatterns = [
    path('', listDonasi, name='list_donasi')
]

form_donasi/urls.py
from django.conf.urls import url
from django.urls import path

from .views import form_donasi_post, index

app_name = 'form_donasi'

urlpatterns = [
    path('', index, name='index'),
    path('form_donasi_post', form_donasi_post, name='form_donasi_post')
]

program/urls.py
from django.urls import path
from .views import program_view

urlpatterns = [
    path('<str:judul>', program_view)
]

templates/footer.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/GeneralStyle.css' %}">
<div class="footer">
    <div class="container_sosmed">
        <div class="logo_footer"><img src="{% static 'img/LOGOO2.png' %}"></div>
        <div class="sosial_media">
            <p class="subjudul">Temukan kami di:</p>
            <div class="icon">
                <div class="icon_sosmed"><img src="{% static 'img/round_btn_facebook.png' %}"></div>
                <div class="icon_sosmed"><img src="{% static 'img/round_btn_instagram.png' %}"></div>
                <div class="icon_sosmed"><img src="{% static 'img/round_btn_google.png' %}"></div>
            </div>
        </div>
    </div>
</div>

<div class="footer_info">
    <div class="container_info">
        <div class="info">
            <h1 class="judul_info">Yayasan SinarPerak</h1>
            <p class="subjudul_info">Jl. Margonda Raya , Pondok Cina, <br> Depok, Jawa Barat <br>
                +6281 - 234 - 5678 <br>
                +6287 - 709 - 8976 <br>
                tebarkankebaikan@sinarperak.org</p>
        </div>

        <div class="info">
            <h1 class="judul_info">Tentang Kami</h1>
            <p class="subjudul_info">Sinar-perak.com adalah website untuk <br> berdonasi secara online dan transparan. <br>
                Bersama Sinar Perak, sinari senyuman <br> orang - orang yang membutuhkan. <br> Aku, Kamu, Kita sama - sama
                peduli. </p>
        </div>

        <div class="info">
            <h1 class="judul_info">Program Kami</h1>
            <p class="subjudul_info">Galang dana <br> Donasi </p>
        </div>
    </div>
</div>

templates/navbar.html
{% load staticfiles %}
<script src="{%static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{%static 'js/bootstrap/popper.min.js'%}"></script>
    <!-- Bootstrap js -->
    <script src="{%static 'js/bootstrap/bootstrap.min.js'%}"></script>
    <!-- All Plugins js -->
    <script src="{%static 'js/plugins/plugins.js'%}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/GeneralStyle.css' %}">
<script src="{% static 'js/navbar.js' %}"></script>

<!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand active" href="{% url 'landingpage' %}"><img src="{% static 'img/logo.png' %}" style="width:100px;"><span class="sr-only">(current)</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link" href="{% url 'landingpage' %}#landingpage">BERANDA</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'form_donasi:index' %}">DONASI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tentangKami' %}">TENTANG KAMI</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}#register">DAFTAR</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link dropbtn" href="#" onclick="dropFunction()">{{user.first_name}} {{user.last_name}}</a>
                        <div id="myDropdown" class="dropdown-content">
                            <a href="{% url 'logout' %}">Logout</a>
                            <a href="{% url 'daftardonasi:list_donasi' %}">Donasi Saya</a>
                        </div>
                    {% else %}
                    <a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}">LOGIN</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>